// Mapeamento de slugs para nomes mais bonitos
export const breadcrumbNames: Record<string, string> = {
  produtos: 'Produtos',
  servicos: 'Serviços',
  'cobertura-retratil': 'Cobertura Retrátil',
  'cobertura-policarbonato': 'Cobertura em Policarbonato',
  'cobertura-termoacustica': 'Cobertura Termoacústica',
  'veneziana-policarbonato': 'Veneziana em Policarbonato',
  'cobertura-area-gourmet': 'Cobertura para Área Gourmet',
  'cobertura-piscina': 'Cobertura para Piscina',
  'cobertura-pergolado': 'Cobertura para Pergolado',
  'cobertura-garagem': 'Cobertura para Garagem',
  'cobertura-corredor-lateral': 'Cobertura para Corredor Lateral',
  'cobertura-playground': 'Cobertura para Playground',
  'cobertura-aluminio': 'Cobertura de Alumínio',
  'projetos-personalizados': 'Projetos Personalizados',
  'policarbonato-compacto': 'Policarbonato Compacto',
  'policarbonato-alveolar': 'Policarbonato Alveolar',
  'automacao-inteligente': 'Automação Inteligente',
  localizacao: 'Localização',
  'sao-paulo': 'São Paulo',
  'zona-leste': 'Zona Leste',
  'zona-sul': 'Zona Sul',
  'zona-norte': 'Zona Norte',
  'zona-oeste': 'Zona Oeste',
  brooklin: 'Brooklin',
  jardins: 'Jardins',
  moema: 'Moema',
  mooca: 'Mooca',
  morumbi: 'Morumbi',
  pinheiros: 'Pinheiros',
  tatuape: 'Tatuapé',
  'vila-mariana': 'Vila Mariana',
  blog: 'Blog',
  sobre: 'Sobre Nós',
  contato: 'Contato',
  orcamento: 'Orçamento',
  faq: 'Perguntas Frequentes',
  cases: 'Cases de Sucesso',
  'cases-sucesso': 'Cases de Sucesso',
};
